name: Cageball import
on:
  schedule:
    - cron: "0 6-23 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call import cageball endpoint
        run: |
          curl --url 'https://joga-bonito.vercel.app/api/cageball/import'
